[package]
name = "mcfpm"
version = "0.1.0"
authors = ["toliner <toliner.rkt@gmail.com>"]
description = "Minecraft Forge Package Manager with CurseForge"

[dependencies]
clap = "2.31.2"
serde_json = "1.0.16"
hyper-rustls = "0.12.0"